# this bot will update the dependencies automatically so we don't have to
version: 2
updates:
  # backend: looks in AetherXmlBridge/aetherxmlbridge/pom.xml
  - package-ecosystem: "maven"
    directory: "/aetherxmlbridge"
    schedule:
      interval: "weekly"
    groups:
      maven-dependencies:
        patterns:
          - "*"

  # docker: keeps Java/Base images updated
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eclipse-temurin"
        versions: [">= 22"]
      - dependency-name: "node"
        versions: [">= 21"]
    groups:
      docker-dependencies:
        patterns:
          - "*"