# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Zoho OAuth .ca config
spring.security.oauth2.client.registration.zoho.client-id=${ZOHO_CLIENT_ID}
spring.security.oauth2.client.registration.zoho.client-secret=${ZOHO_CLIENT_SECRET}
spring.security.oauth2.client.registration.zoho.scope=AaaServer.profile.READ,ZohoCreator.report.READ
spring.security.oauth2.client.registration.zoho.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.zoho.redirect-uri={baseUrl}/login/oauth2/code/zoho
spring.security.oauth2.client.registration.zoho.client-name=Zoho
spring.security.oauth2.client.registration.zoho.client-authentication-method=client_secret_post

# Zoho Provider URLs (global/US domain , accounts-server=https://accounts.zoho.com)
spring.security.oauth2.client.provider.zoho.authorization-uri=https://accounts.zoho.com/oauth/v2/auth
spring.security.oauth2.client.provider.zoho.token-uri=https://accounts.zoho.com/oauth/v2/token
spring.security.oauth2.client.provider.zoho.user-info-uri=https://accounts.zoho.com/oauth/user/info
spring.security.oauth2.client.provider.zoho.user-name-attribute=Email

# logging
logging.level.org.springframework.security.oauth2.client=TRACE
logging.level.org.springframework.web.client=DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
