spring.application.name=aetherxmlbridge

# local development h2 configuration (Render env vars override these)
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:aetherdb}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# Automatically create and update the schema from JPA entities.
spring.jpa.hibernate.ddl-auto=update
# SQL logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}

spring.thymeleaf.mode=HTML

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ai agent
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

# Testing
spring.profiles.active=dev

